---
- name: delete the vm instance, gcp disk, and firewall rule
  hosts: localhost
  gather_facts: no

  vars_files:
    - vars/vars-netops.yml

  tasks:
    - name: check for existing vm instance
      command: >
        gcloud compute instances describe {{ vm_name }}
        --zone {{ zone }}
      register: server
      changed_when: no
      ignore_errors: yes

    - name: delete the vm instance
      command: >
        gcloud compute instances delete {{ vm_name }}
        --zone {{ zone }}
        --quiet
      when: server.rc == 0

    - name: check for existing disk
      command: >
        gcloud compute disks describe {{ disk_name }}
        --zone {{ zone }}
      register: disk 
      changed_when: no
      ignore_errors: yes

    - name: delete the disk
      command: >
        gcloud compute disks delete {{ disk_name }}
        --zone {{ zone }}
        --quiet
      when: disk.rc == 0

    - name: check for existing firewall rule (openvpn)
      command: >
        gcloud compute firewall-rules describe {{ fr_name }}
      register: firewall
      changed_when: no
      ignore_errors: yes

    - name: delete the firewall rule (openvpn)
      command: >
        gcloud compute firewall-rules delete {{ fr_name }}
        --quiet
      when: firewall.rc == 0