---
- name: temp play
  hosts: localhost
  gather_facts: no

  vars_files:
    - vars/vars-gcp.yml
  
  tasks:
    - name: create the firewall rule (openvpn)
      command: >
        gcloud compute firewall-rules create {{ fr_name }}
        --direction=INGRESS
        --priority=1000
        --network=default
        --action=ALLOW
        --rules=udp:1194
        --source-ranges=0.0.0.0/0
        --target-tags={{ net_tag }}