---
- name: install and configure netops components
  hosts: vm1
  connection: ssh
  remote_user: wamer
  become: yes
  become_method: sudo

  vars_files:
    - vars/vars-netops.yml
  
  tasks:
    - name: get and install openvpn package
      yum:
        name: openvpn
        state: present
      become: yes
  
  handlers:
    - name: restart openvpn
      service:
        name: openvpn-server@server
        state: restarted
      become: yes
    