---
- name: check for existing disk
  command: >
    gcloud compute disks describe {{ disk_name }}
    --zone {{ zone }}
  register: disk 
  changed_when: no
  ignore_errors: yes

- name: create the disk
  command: >
    gcloud compute disks create "{{ disk_name }}"
    --size "{{ disk_size }}"
    --type "{{ disk_type }}"
    --zone {{ zone }}
    --image-project ubuntu-os-cloud
    --image-family "{{ vm_os }}"
    --licenses 'https://www.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx'
    --quiet
  when: disk.rc != 0

- name: check for existing firewall rule (openvpn)
  command: >
    gcloud compute firewall-rules describe {{ fr_name }}
  register: firewall
  changed_when: no
  ignore_errors: yes

- name: create the firewall rule (openvpn)
  command: >
    gcloud compute firewall-rules create {{ fr_name }}
    --direction=INGRESS
    --priority=1000
    --network=default
    --action=ALLOW
    --rules=udp:1194
    --source-ranges=0.0.0.0/0
    --target-tags={{ net_tag }}
  when: firewall.rc != 0

- name: check for existing vm instance
  command: >
    gcloud compute instances describe {{ vm_name }}
    --zone {{ zone }}
  register: server
  changed_when: no
  ignore_errors: yes

- name: create the instance
  command: >
    gcloud compute instances create {{ vm_name }}
    --zone {{ zone }}
    --machine-type {{ vm_type }}
    --min-cpu-platform "{{ vm_cpu }}"
    --disk name={{ disk_name }},boot=yes
    --network-interface subnet=sub10
    --can-ip-forward
    --tags {{ net_tag }}
    --metadata startup-script='apt-get -qq update'
  when: server.rc != 0

- name: pause to allow update to complete
  pause:
    minutes: 1
  when: server.rc != 0

